### ISSUE TITLE
Spring

### ISSUE THREAD

**Issue by jsgounot** [mbhall88/compression_benchmark#7]
Hi,

I found this post a bit randomly but I found it quite interesting. I'd suggest adding [Spring](https://github.com/shubhamchandak94/Spring) if there is a plan to make another iteration in the future. We can ignore [NanoSpring](https://github.com/qm2/NanoSpring) as it is a lossy compressor compared to Spring. Spring works much better with Illumina reads compared to Nanopore.

By the way, I don't know if µbioinfo is a private or public group, but if it's public I'd be happy to join!

Have a nice day,
JS

**Comment by mbhall88** [comment]
Glad you found it interesting. And thank you for the suggestion.

Regarding adding spring to the benchmark, I'll first reiterate something I say in the readme

> Don't get me wrong, there are plenty of benchmarks, but they're always looking at bioinformatics-specific tools for compressing sequencing data. Sure, these perform well, but every repository I went to was untouched in a while. When archiving data, the last thing I want is to try and decompress my data and the tool no longer installs/works on my system. In addition, I want the tool to be ubiquitous and mature. I know this is a lot of constraints, but hey, that's what I am interested in.

It does look like spring has some recent-ish activity, which is nice. But I guess it's more a question of will it be maintained in say 5 years time when I want to use it and potentially run into problems? As I say, I wanted this benchmark to focus more on the general-type compression algorithms rather than the specialised ones, which has plenty of benchmarking in the literature.

If you really want spring in the benchmark I would happily receive a pull request though.

**Comment by mbhall88** [comment]
As for the µbioinfo slack channel, do you work in microbial bioinformatics?

**Comment by jsgounot** [comment]
Yes makes sense. Just as general info, I observe a compression ratio of 16 with Illumina reads, so similar to what you see with `xz` I assume. 

> As for the µbioinfo slack channel, do you work in microbial bioinformatics?
Yes, mostly [metagenomic assembly](https://www.nature.com/articles/s41467-022-33782-z) and [strain phasing](https://academic.oup.com/bioinformatics/article/40/Supplement_1/i30/7700908?login=false) lately.

**Comment by mbhall88** [comment]
Cool! Is there an institutional email or another email I can use to invite you to the slack?
